### PR TITLE
feat(install): add checksum verification and install fixes

### LINKED ISSUE #90: Improvements in install command
## Current Issues
1. Installation failures:
   - Incorrect temporary directory handling
   - Failed extractions and file copying
   - Missing checksum verification
   - Linker errors (`libwasmedge.so.0` not found)
   - Wrong environment setup for Unix (It's sourcing `bin/env/env`, but `/bin/env` is the file )

2. No version management:
   - Overwrites existing installations
   - Can't switch between versions

### 1. Directory Structure
```bash
~/.wasmedge/
├── versions/              
│   ├── 0.13.5/          # Version-specific directories
│   │   ├── bin/
│   │   ├── lib64/
│   │   └── include/
│   └── 0.15.0/
└── current -> versions/0.15.0/  # Active version symlink
```

### 2. Installation Process
- Download with checksum verification
- Extract directly to version directory
- Create proper symlinks
- Set up environment (PATH, LD_LIBRARY_PATH)

### 3. Version Management Commands
```bash
# Install specific/latest version
wasmedgeup install 0.15.0
wasmedgeup install latest

# Switch versions
wasmedgeup use 0.15.0

# Remove version
wasmedgeup remove 0.15.0
```

### 4. Security
- Add SHA256 checksum verification.

## References
- [POC Recorded Implementation](https://gist.github.com/Arshdeep54/9e61481e8143981ee9bef970bbce92bf#demo)
- [Demo Implementation Repo](https://github.com/Arshdeep54/wasmedgeup-demo/) 
- [LFX Workspace](https://github.com/WasmEdge/WasmEdge/issues/4351)

### PR DESCRIPTION
**Pull request by Arshdeep54**
## Which GitHub issue does this PR close?

Closes #90 

## Why is this needed?
To fix the installation function and add checksum verification.

## What does this PR change?
The PR fixes the following 
```
Incorrect temporary directory handling
Failed extractions and file copying
Missing checksum verification
Linker errors (libwasmedge.so.0 not found)
Wrong environment setup for Unix (It's sourcing bin/env/env, but /bin/env is the file )
```

## How has this been tested?
Added unit tests for the checksum verification. 

Related : [Wasmedge#4351](https://github.com/WasmEdge/WasmEdge/issues/4351)

### CODE REVIEW

**Comment by hydai** [comment]
Have you ever run the test suites in your own environment, or do you just send an unverified and untested PR to me and ask for the review process?

File: src/api/mod.rs [hunk 1]
```diff
@@ -57,6 +64,92 @@ impl WasmEdgeApiClient {
...
+
+        Err(Error::ChecksumNotFound {
+            version: version.to_string(),
+            asset: asset.archive_name.clone(),
+        })
+    }
+
+    pub async fn verify_file_checksum(file: &mut std::fs::File, expected: &str) -> Result<()> {
+        let mut hasher = Sha256::new();
+        let mut buffer = [0; 8192];
```
Comment (hydai) [inline src/api/mod.rs:132]: What's the reason for using a size of 8192 here? What will happen if the file is larger than this size?

File: src/shell_utils/env.fish [hunk 2]
```diff
@@ -5,3 +5,9 @@ if not contains "{WASMEDGE_BIN_DIR}" $PATH
     # Prepending path
     set -gx PATH "{WASMEDGE_BIN_DIR}" $PATH
 end
+
+# Handle LD_LIBRARY_PATH
+if not contains "{WASMEDGE_LIB_DIR}" $LD_LIBRARY_PATH
```
Comment (hydai) [inline src/shell_utils/env.fish:10]: Please notice that LD_LIBRARY_PATH is only for Linux. macOS uses `DYLD_LIBRARY_PATH`.

File: src/shell_utils/env.fish [hunk 3]
```diff
@@ -5,3 +5,9 @@ if not contains "{WASMEDGE_BIN_DIR}" $PATH
...
+    # Prepending library path
+    set -gx LD_LIBRARY_PATH "{WASMEDGE_LIB_DIR}" $LD_LIBRARY_PATH
+end
```
Comment (hydai) [inline src/shell_utils/env.fish:13]: EOF issue.

File: src/shell_utils/env.nu [hunk 4]
```diff
@@ -4,3 +4,5 @@
 use std/util "path add"
 
 path add "{WASMEDGE_BIN_DIR}"
+
+path add "{WASMEDGE_LIB_DIR}" LD_LIBRARY_PATH
```
Comment (hydai) [inline src/shell_utils/env.nu:8]: Ditto.

File: src/shell_utils/env.sh [hunk 5]
```diff
@@ -11,3 +11,13 @@ case ":${PATH}:" in
...
+
+# Handle LD_LIBRARY_PATH
+case ":${LD_LIBRARY_PATH:=}:" in
+    *:"{WASMEDGE_LIB_DIR}":*)
+        ;;
+    *)
+        # Prepending library path
+        export LD_LIBRARY_PATH="{WASMEDGE_LIB_DIR}:${LD_LIBRARY_PATH}"
+        ;;
+esac
```
Comment (hydai) [inline src/shell_utils/env.sh:23]: Ditto.

File: src/shell_utils/unix.rs [hunk 6]
```diff
@@ -86,8 +84,12 @@ pub trait UnixShell: Send + Sync {
 
     fn write_script(&self, script: &ShellScript, install_dir: &Path) -> Result<()> {
         let wasmedge_bin = format!("{}/bin", install_dir.to_string_lossy());
+        let wasmedge_lib = format!("{}/lib64", install_dir.to_string_lossy());
```
Comment (hydai) [inline src/shell_utils/unix.rs:87]: Not all library paths are located under `lib64`; please check the original installer script for details.

**Review by hydai — CHANGES_REQUESTED** [review]

File: src/api/mod.rs (hunk 1 above)
Comment (Arshdeep54) [reply src/api/mod.rs]: I was trying to maintain the constant memory usage using the fixed-size buffer to compute the file's hash.
Using `fs::read` would load the entire file into memory at once, which could be problematic for large files.
So that's why I chose 8KB for the buffer size (usual system page size) because at the end it will hash the whole file.

Am I missing anything here?

Comment (hydai) [reply src/api/mod.rs]: Did you check the size of `SHA256SUM` on the WasmEdge release page? If so, what is the reason for using 8 KB?

I still have no idea what the benefit of using a fixed-size buffer here is. You can run a benchmark and tell me the performance improvement of using a fixed-size buffer versus a dynamically sized buffer when this file is less than 100 KB.

Comment (Arshdeep54) [reply src/api/mod.rs]: I think there is a misunderstanding in explaining by my side. The `verify_file_checksum` function takes the downloaded asset file (WasmEdge-0.15.0-Linux ~50MB) as input `file`, computes its hash, and compares it against the expected hash from the SHA256SUM file.

This is why I chose not to use `fs::read()`, which would load the entire 50MB asset into memory at once.
`SHA256SUM` is just of 12KB and that's the `expected` hash which I am just comparing at the end.

Comment (hydai) [reply src/api/mod.rs]: I see, I misunderstood the part you mentioned.

**Comment by Arshdeep54** [comment]
> Could you please add more tests to cover the installation verification? As your previous commits indicate, the DYLD_LIBRARY_PATH is not handled; however, all tests pass, which suggests that this behavior is not verified by the current test suite.

I have added the [shell utils tests](https://github.com/Arshdeep54/wasmedgeup/blob/install-fixes/tests/shell_test.rs). Let me know if any other tests are required.

File: src/commands/install.rs [hunk 7]
```diff
@@ -21,6 +22,14 @@ fn default_tmpdir() -> PathBuf {
     std::env::temp_dir()
 }
 
+fn get_system_install_info() -> (String, String) {
+    if cfg!(windows) {
+        ("C:\\Program Files\\WasmEdge".to_string(), "".to_string())
```
Comment (hydai) [inline src/commands/install.rs:27]: Just want to know if this is the default installation path for all Windows platforms.

File: src/commands/install.rs [hunk 8]
```diff
@@ -82,35 +83,80 @@ impl CommandExecutor for InstallArgs {
...
 
         let asset = Asset::new(&version, os, arch);
-        let tmpdir = self.tmpdir.unwrap_or_else(default_tmpdir);
-        let file = ctx
+        let base_tmpdir = self.tmpdir.unwrap_or_else(default_tmpdir);
+
+        let tmpdir = base_tmpdir.join(&asset.install_name);
+        fs::create_dir_all(&tmpdir).await.inspect_err(
+            |e| tracing::error!(error = %e.to_string(), "Failed to create temporary directory"),
+        )?;
```
[the remark this answers is not in the document]
Comment (hydai) [reply src/commands/install.rs:100]: I mean, you should write the design decision in the comments so people can understand how we handle these situations, instead of explaining the logic in a PR.

File: src/commands/install.rs [hunk 9]
```diff
@@ -82,35 +91,110 @@ impl CommandExecutor for InstallArgs {
...
-        crate::fs::copy_tree(&extracted_dir, &target_dir).await;
+        let mut read_dir = fs::read_dir(&tmpdir).await?;
+        let mut source_dir = tmpdir.clone();
+
+        if let Some(entry) = read_dir.next_entry().await? {
+            let file_name = entry.file_name().into_string().unwrap_or_default();
+            if file_name.starts_with("WasmEdge-") && entry.file_type().await?.is_dir() {
+                source_dir = entry.path();
+            } else if !matches!(file_name.as_str(), "bin" | "lib64" | "include" | "lib") {
+                return Err(Error::Unknown);
```
Comment (hydai) [inline src/commands/install.rs:182]: We should have a detailed error here instead of `Unknown`. For example, since the file_name does not match the allowlist, we should indicate the retrieved file name to report to users so that we can also obtain the error log for debugging.

**Review by hydai — CHANGES_REQUESTED** [review]
